### ISSUE TITLE
AndroidManifest.xml with allowBackup and supportsRtl attributes in application section

### ISSUE THREAD

**Issue by richardgarcar** [sqlcipher/sqlcipher-android#10]
Hello.

Would it be possible to remove `allowBackup` and `supportsRtl` attributes from application section in [AndroidManifest.xml](https://github.com/sqlcipher/sqlcipher-android/blob/729b52f39de33ac3b54f695c2bc9d511b2d83f9c/sqlcipher/src/main/AndroidManifest.xml)? Integration of the library to the application with different setting for either `allowBackup` or `supportsRtl` requires workaround solutions. In addition, [Manifest](https://github.com/sqlcipher/android-database-sqlcipher/blob/9483458c693ca6f4e511ffa0c016996d8ac71794/android-database-sqlcipher/src/main/AndroidManifest.xml) in the original library does not contain `application` section at all.

**Comment by developernotes** [comment]
Hi @richardgarcar,

I have removed the `application` block and renamed the package [here](https://github.com/sqlcipher/sqlcipher-android/commit/454149c8c4242bf0b4a805bdf979fe7eed4953ac). This will be included in the next public release. Thanks for the suggestion!
