### ISSUE TITLE
Create consumer proguard rules

### ISSUE THREAD

**Issue by almozavr** [sqlcipher/sqlcipher-android#18]
### Issue
By default sqlcipher-android doesn't support Proguard, so andorid's R8 rips out valuable information, e.g.
```
 no "Ljava/lang/String;" field "name" in class "Lnet/zetetic/database/sqlcipher/SQLiteCustomFunction;" or its superclasses
 ```

### Solution
Add `consumer-rules.pro` to the project, so it's included in `aar`.

P.S.
Currently we use this, but probably it's an overkill
```
-keep,includedescriptorclasses class net.zetetic.database.** { *; }
-keep,includedescriptorclasses interface net.zetetic.database.** { *; }
```

**Comment by developernotes** [comment]
Hi @almozavr,

Sorry for the late reply, this is a good idea. Would you be interested in submitting a pull request for this? If so, we have a contributor license agreement [^1]. Please reach out to us at [support@zetetic.net](mailto:support@zetetic.net).

[^1]: https://www.zetetic.net/contributions/

**Comment by eygraber** [comment]
This was addressed by https://github.com/sqlcipher/sqlcipher-android/pull/24

**Comment by developernotes** [comment]
Hi @almozavr,

I am circling back to this ticket to see if you are interested in evaluating a new beta build of SQLCipher for Android which includes improved consumer ProGuard rules. We have shared additional information about this in #78. Please feel free to reach out if you're interested in evaluating the new build.

Thank you,
