### ISSUE TITLE
where is the sqlite3.c and sqlite3.h file for android build?

### ISSUE THREAD

**Issue by largeriver1** [sqlcipher/sqlcipher-android#19]
Hello. 
In the page below, I need sqlite3.c and sqlite3.h file for android build.
https://github.com/sqlcipher/sqlcipher-android

<project-root>/sqlcipher/src/main/jni/sqlcipher/sqlite3.c
<project-root>/sqlcipher/src/main/jni/sqlcipher/sqlite3.h

So I downloaded sqlite-amalgamation-3420000.zip file in https://www.sqlite.org/download.html.
And then I copied sqlite3.c and sqlite3.h file to /sqlcipher/src/main/jni/sqlcipher/
But build errors below occurred.

use of undeclared identifier 'sqlite3_key'
use of undeclared identifier 'sqlite3_rekey'

There is no sqlite3_key and sqlite3_rekey in sqlite3.c and sqlite3.h file I downloaded.
Did I download the wrong file?
Where can I get the sqlite3.c and sqlite3.h files?

Thank you.

**Comment by developernotes** [comment]
@largeriver1 you will need to prepare the amalgamation from the SQLCipher [^1] repo, you can review the steps in this [^2] introduction document. Please make sure you include `-DSQLITE_HAS_CODEC`. If you have further questions about building, please feel free to post those to the SQLCipher Community Discuss site [^3].

[^1]: https://github.com/sqlcipher/sqlcipher
[^2]: https://www.zetetic.net/sqlcipher/introduction/
[^3]: https://discuss.zetetic.net/c/sqlcipher
