### ISSUE TITLE
Android 13 issue on database encryption

### ISSUE THREAD

**Issue by ShraddhaGade** [sqlcipher/sqlcipher-android#21]
Hi 

I m using room database and sqlcipher-android for database encryption. ITs working fine when I m installing application from android studio.

But when I make application as a system app in android 13, its not behaving properly. I m not getting data from data base. Without using sqlcipher-android(only with room database but without encryption) application as a system app is behaving properly. My database table structure is very simply its like 
ID,KEY , value is a column. I m using screen with 2 edittext one for key and one is for value in a screen. User enters it and save it. But select * from table is not giving me those data which is saved. Please note this is only not happening when we make application as a system app in android 13. In android 11 its working fine.

**Comment by developernotes** [comment]
Hi @ShraddhaGade,

Are you testing the system application on a rooted device, or are you using the signing key of the firmware? Can you confirm the output from the database library when you execute the following within your system application:

```
PRAGMA cipher_version;
```

Is your application operating on an existing database file, or is it creating it? If it's existing, was it previously encrypted with SQLCipher, or was it a plaintext database?

**Comment by ShraddhaGade** [comment]
HI @developernotes  In aosp code I m making my application as a system app , signing application using keystore.
application is fresh only so there was not database before. Application is creating a new database.

**Comment by developernotes** [comment]
Hello @ShraddhaGade,

Would you please check the output of executing `PRAGMA cipher_version;` and report the string value returned from your application? This will be helpful in debugging your scenario.

**Comment by ShraddhaGade** [comment]
Hi @developernotes sry for raising this here but seems like this is default behavior in android with out integrating with sql chipher issue is still coming. Sorry that raised here but its not related to this now I got it.
