### ISSUE TITLE
SqlCipher binaries are almost twice the size of android-database-sqlcipher

### ISSUE THREAD

**Issue by eygraber** [sqlcipher/sqlcipher-android#26]
Not sure if there's anything to do about this or not, but the size of libsqlcipher.so has almost doubled after updating from android-database-sqlcipher to sqlcipher-android

android-database-sqlcipher
![image](https://github.com/sqlcipher/sqlcipher-android/assets/1100381/f6034f89-42a9-4c31-9c2d-7de97e6052a0)

sqlcipher-android
![image](https://github.com/sqlcipher/sqlcipher-android/assets/1100381/376c3a06-c163-4a12-b716-e698296e3a4c)

**Comment by developernotes** [comment]
Hi @eygraber,

What are the two versions you are comparing of `android-database-sqlcipher` and `sqlcipher-android`?

**Comment by eygraber** [comment]
android-database-sqlcipher: 4.5.4
sqlcipher-android: 4.5.5

**Comment by developernotes** [comment]
Hi @eygraber,

I would suggest comparing the native file sizes of the same version releases for maintaining consistency. You can see below with version `4.5.4`, the native file sizes are much more similar:

<img width="1041" alt="native-file-sizes" src="https://github.com/sqlcipher/sqlcipher-android/assets/3225/6f5a19bb-7c96-4e01-b8f3-cd07d6d27375">

Moving to SQLCipher 4.5.5 specifically, libraries which use OpenSSL, which include `sqlcipher-android` moved to OpenSSL 3.0.10 LTS, whereas `android-database-sqlcipher` used OpenSSL 1.1.1t.

**Comment by eygraber** [comment]
Ok I figured it was something like that. Thanks!

**Comment by developernotes** [comment]
No problem at all!

**Comment by UKMIITB** [comment]
@developernotes 
So when we migrate to `sqlcipher-android: 4.5.5` from `android-database-sqlcipher: 4.5.4` , it is bound to increase the app size further by around 3.5mb ?
This is the app size difference we are observing when we carried out the migration.
Is there anyway to limit this ?

**Comment by developernotes** [comment]
Hi @UKMIITB,

The majority of the file size within the AAR is due to the ABI-specific builds of SQLCipher core. The library ships with both 32 and 64-bit versions of x86 and ARM ABI's. You could choose to remove certain ABI's via [`splits`](https://developer.android.com/build/configure-apk-splits), however, if you are deploying via Android App Bundles, the Google Play store will generate and serve optimized APK's for each device configuration so your end user isn't downloading all targets.

**Comment by UKMIITB** [comment]
@developernotes 
Yes agreed that total size increase won't be 3.5mb
But even for single configuration its coming out roughly 1mb more.

**Comment by developernotes** [comment]
Hi @UKMIITB,

Unfortunately, you will not likely be able to decrease the package size much further. If that dependency is too large for your application, you may need to reconsider SQLCipher for your requirements.
