### ISSUE TITLE
Migrating from community edition to commercial edition

### ISSUE THREAD

**Issue by UKMIITB** [sqlcipher/sqlcipher-android#30]
Hi Team,
It's not an issue & more of a question.
We are using community edition of this library & I believe there exists a commercial edition which says it has 3-4X performance improvement.
In our application performance is of great concern & we are willing to invest in getting any type of improvement.

So few questions:
1. We are using this with roomDB in our Android application. So will there be better read & write speeds when we shift to commercial edition.
2. How much would be the performance improvement in terms of read speed. Are there any exact numbers related to it?
3. There is a free trial option available. Is there a way wherein we could test it with our app & see how much improvement we are getting when shifting to commercial edition.
4. Is there any migration doc for moving from community edition to commercial edition? As currently we are already live with community edition of this library

**Comment by developernotes** [comment]
Hi @UKMIITB,

The performance improvements found between Community and Commercial edition builds of SQLCipher may vary based on platform, CPU, cryptographic provider, and most importantly the specific workload that you are using with the database. For this reason, it is very hard to generalize. Please consider the general performance optimization guidance available here [^1].

We do have free trials available upon request [^2] here if you wish to evaluate the Commercial offering. In terms of migrating from Community to Commercial with `sqlcipher-android`, we provide integration guidance here [^3]. If you have any more specific questions regarding Commercial licensing, please feel free to reach out to us at [support@zetetic.net](mailto:support@zetetic.net).

[^1]: https://www.zetetic.net/sqlcipher/performance
[^2]: https://www.zetetic.net/sqlcipher/trial/
[^3]: https://www.zetetic.net/sqlcipher/sqlcipher-for-android/
