### ISSUE TITLE
Add custom function with return not supported?

### ISSUE THREAD

**Issue by Xinkle** [sqlcipher/sqlcipher-android#31]
```
    /**
     * A callback interface for a custom sqlite3 function.
     * This can be used to create a function that can be called from
     * sqlite3 database triggers.
     * @hide
     */
    public interface CustomFunction {
        public void callback(String[] args);
    }
```

I found an interface like the one above for adding a Custom Function, but it's not usable because I can't set the return value. Is there any other way to do this?

**Comment by developernotes** [comment]
Hi @Xinkle,

Could you use a callback function to expose the results, similar to [this](https://github.com/sqlcipher/sqlcipher-android/blob/master/sqlcipher/src/main/java/net/zetetic/database/sqlcipher/SQLiteCustomFunction.java) approach?

**Comment by Xinkle** [comment]
i implemented new method for create sqlite3 function via jni. thanks!
