### ISSUE TITLE
Change log for 4.5.6

### ISSUE THREAD

**Issue by UKMIITB** [sqlcipher/sqlcipher-android#33]
It looks like new version has been published for this.
Can you add in release & share the change log for this

Also the documentation recommends using sqlite 2.2.0, but 2.4.0 is available now.
Any chance of testing this with latest version & officially updating the documentation

**Comment by developernotes** [comment]
Hello @UKMIITB,

Thank you for your interest in SQLCipher for Android. The changes included within the 4.5.6 of SQLCipher for Android can be found [here](https://github.com/sqlcipher/sqlcipher-android/compare/v4.5.5...v4.5.6). SQLCipher core, which is included within SQLCipher for Android includes a changelog [here](https://github.com/sqlcipher/sqlcipher/blob/master/CHANGELOG.md). The main adjustments with the Android library in this release are:

- Fix to close non-primary connections from the pool when changing the password
- Adding ProGuard support
- Include a license file
- Update README documentation

We will consider documentation communication for a future release, along with the update to the sqlite reference.
