### ISSUE TITLE
Support Kotlin Multiplatform

### ISSUE THREAD

**Issue by kingsword09** [sqlcipher/sqlcipher-android#35]
[Official SQLite](https://developer.android.com/kotlin/multiplatform/sqlite) supports kotlin multiplatform. Considering following up on support?

**Comment by developernotes** [comment]
Hello @kingsword09,

Thank you for your interest in SQLCipher. At this time we do not have immediate plans to support the Kotlin Multiplatform implementation via `SQLiteDriver`, `SQLiteConnection`, and `SQLiteStatement`. If you have Commercial interest in this, please feel free to reach out to us privately to discuss Commercial bespoke package offerings at [support@zetetic.net](mailto:support@zetetic.net). Thanks!
