### ISSUE TITLE
Case when password is lost

### ISSUE THREAD

**Issue by UKMIITB** [sqlcipher/sqlcipher-android#41]
How do I handle the case when DB's password is lost
And in this case it should drop the DB & create a new DB
Or drop all tables & create new tables with new password ?

**Comment by developernotes** [comment]
Hello @UKMIITB,

Thanks for your interest in SQLCipher. We reserve GitHub Issues for tracking defects within the software library itself. This particular question should be posted to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher), please consider reposting there instead. Thanks!

**Comment by UKMIITB** [comment]
Sure will do
Thanks
