### ISSUE TITLE
Android 15 - 16kb Page Size

### ISSUE THREAD

**Issue by jamesthacker** [sqlcipher/sqlcipher-android#42]
Android 15 is adding support for 16kb page sizes: https://developer.android.com/about/versions/15/behavior-changes-all#16-kb

Following the steps outlined [here](https://developer.android.com/guide/practices/page-sizes#test), SQLCipher shows as unaligned:
```
./jni/arm64-v8a/libsqlcipher.so: UNALIGNED (2**12)
```

Are there plans to recompile the native library in order to support 16kb page sizes?

**Comment by developernotes** [comment]
Hi @jamesthacker,

Yes, we are planning to support the 16k page size in the next release [^1].

[^1]: https://discuss.zetetic.net/t/android-sqlcipher-support-for-android-sdk-35-16k-page-sizes/6460
