### ISSUE TITLE
How to hook onCreate and onUpgrade?

### ISSUE THREAD

**Issue by kurupted** [sqlcipher/sqlcipher-android#43]
eg like this:

    override fun onCreate(db: SQLiteDatabase) {
        createTables(db)
    }

    override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) {
        if (oldVersion < 2) {
            db.execSQL("ALTER TABLE $TABLE_ENTRIES ADD COLUMN $COLUMN_RATING INTEGER DEFAULT 0")
            db.execSQL("ALTER TABLE $TABLE_ENTRIES ADD COLUMN $COLUMN_BOOKMARKED INTEGER DEFAULT 0")
        }
    }

**Comment by developernotes** [comment]
Hello @kurupted,

Thanks for your interest in SQLCipher. We reserve GitHub Issues for tracking defects within the software library itself. This particular question should be posted to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher), please consider reposting there instead. Thanks!
