### ISSUE TITLE
The sqlcipher.so file is too large. Can you reduce the file size?

### ISSUE THREAD

**Issue by Zangmingchao** [sqlcipher/sqlcipher-android#45]
sqlcipher.so is too big, is there any redundant file? Can the file size be reduced? Compared with android-database-sqlcipher, it is 800k larger

**Comment by developernotes** [comment]
Hi @Zangmingchao,

Thanks for your interest in SQLCipher. We reserve GitHub Issues for tracking defects within the software library itself. This particular question should be posted to the [SQLCipher Community Discuss site](https://discuss.zetetic.net/c/sqlcipher), please consider reposting there instead. Thanks!
