### ISSUE TITLE
"Attempt to get length of null array" when calling update or delete with null whereArgs

### ISSUE THREAD

**Issue by mtotschnig** [sqlcipher/sqlcipher-android#50]
When migrating from android-database-sqlcipher , I noticed that these two problems:
https://github.com/sqlcipher/android-database-sqlcipher/issues/533
https://github.com/sqlcipher/android-database-sqlcipher/issues/615
which had been fixed in android-database-sqlcipher, still exist in sqlcipher-android 

For example, calling SupportSqliteDatabase.delete(table: String, whereClause: String?, whereArgs: Array<out Any?>?) with null as final argument raises:

`java.lang.NullPointerException: Attempt to get length of null array
                                                                                                    	at net.zetetic.database.sqlcipher.SQLiteDatabase.delete(SQLiteDatabase.java:1183)`

**Comment by developernotes** [comment]
Hi @mtotschnig,

What version of `sqlcipher-android` are you using? I noticed we already have [a test](https://github.com/sqlcipher/sqlcipher-android/blob/master/sqlcipher/src/androidTest/java/net/zetetic/database/sqlcipher_cts/SQLCipherDatabaseTest.java#L509-L524) around the `delete` method with a null where argument.

**Comment by mtotschnig** [comment]
@developernotes 4.6.1

**Comment by mtotschnig** [comment]
It seems fixed (https://github.com/sqlcipher/sqlcipher-android/commit/ce1d19ffae1f48e188eeb4b07ae2aeb680ba33d1) but not part of the latest release.

**Comment by developernotes** [comment]
Hi @mtotschnig,

SQLCipher for Android 4.6.1 was released on 8/20/2024 and is our current public release. The changes in [ce1d19f](https://github.com/sqlcipher/sqlcipher-android/commit/ce1d19ffae1f48e188eeb4b07ae2aeb680ba33d1) didn't land until 9/4/2024 and will be included in our next public release, or you may build it locally if you have a more urgent need.

**Comment by mtotschnig** [comment]
@developernotes That's what I figured as well, thanks for confirming. I guess this can be closed then, unless you want to keep it open until the next release.

**Comment by developernotes** [comment]
Hi @mtotschnig,

Great, we will close this ticket for now as those changes will be included in our next public release. Thanks!
